services:
  db:
    container_name: inventory-api
    restart: always
    image: mysql:5.7    
    environment:
      MYSQL_DATABASE: db_inventory
      MYSQL_USER: usr_inventory_api
      MYSQL_PASSWORD: userInventoryApi
      MYSQL_ROOT_PASSWORD: inventory_api123456789*
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      tty: true
    ports:
      - "3306:3306"
    networks:
        - app-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
